repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=5000']
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-executables-have-shebangs

- repo: local
  hooks:
  - id: commitizen
    name: commitizen
    entry: cz check
    args: [--allow-abort, --commit-msg-file]
    language: python
    stages: [commit-msg]
